language: python
python: 2.7
env:
    - TOX_ENV=old
    - TOX_ENV=old-lts
    - TOX_ENV=py27
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=py36
    - TOX_ENV=docs
install: pip install tox
script: tox -e $TOX_ENV
